import { writeFile } from '@hypernym/utils/fs'
import { defineConfig } from './src/config.js'
import { name, version } from './package.json'

export default defineConfig({
  entries: [
    { input: './src/index.ts' },
    { types: './src/types/index.ts' },
    {
      input: './src/bin/index.ts',
      plugins: {
        replace: {
          preventAssignment: true,
          __version__: version,
        },
      },
    },
  ],
  hooks: {
    'build:start': async () => {
      await writeFile(
        './dist/bin/_empty.ts',
        `// Generated by ${name}`,
        'utf-8',
      )
    },
  },
})
